import { CATEGORIES } from "./categories";
import type { ProductColor } from "./product-options";

export type Product = {
  id: string;
  name: string;
  reference?: string;
  description: string;
  category: string;
  subcategory: string;
  price: number;
  oldPrice?: number;
  imageUrl: string;
  images: string[];
  stock: number;
  canniCollection?: string;
  colors: ProductColor[];
  isBestSeller?: boolean;
  isNew?: boolean;
};

const images = {
  vernis: "https://hercules-cdn.com/file_P6Bb0DrBd4FZQXdNswwBIbH6",
  coats: "https://hercules-cdn.com/file_8r6fY6tok9GV86nd3obHx0NV",
  pinceau: "https://hercules-cdn.com/file_0k64ARE9trLk3yCFUeM3TwqG",
  tools: "https://hercules-cdn.com/file_5PMdmdYL1K4dAOwTB9Ql7YyW",
  capsules: "https://hercules-cdn.com/file_kGUpxK72XaaIBgGOIXY7vrxZ",
  gels: "https://hercules-cdn.com/file_UmIrFdNvYGhn1kdpHrsPAtmN",
  decoration: "https://hercules-cdn.com/file_qD1QGZqzNqF1W3KVnpE3x63l",
  pack: `${import.meta.env.BASE_URL}images/categories/pack.png`,
  appareil: "https://hercules-cdn.com/file_J0OFplWLXsf3YDE3UhO57xTp",
  emballage: "https://hercules-cdn.com/file_eL3rYeVaw8CPArGodwBLRiwk",
};

const canniImage = (collection: string) =>
  `${import.meta.env.BASE_URL}images/canni/${collection}.webp`;

export const PRODUCTS: Product[] = [
  {
    id: "canni-cc1",
    name: "Vernis Canni CC1",
    reference: "CC1",
    description: "Vernis gel professionnel, couvrance élégante et tenue brillante pour poses salon.",
    category: "vernis",
    subcategory: "canni",
    price: 850,
    oldPrice: 1000,
    imageUrl: canniImage("cc1"),
    images: [canniImage("cc1")],
    stock: 20,
    canniCollection: "cc1",
    colors: [
      { name: "Rouge", value: "#ef4444" },
      { name: "Bleu", value: "#2563eb" },
      { name: "Rose", value: "#ec4899" },
    ],
    isBestSeller: true,
  },
  {
    id: "canni-cc2",
    name: "Vernis Canni CC2",
    reference: "CC2",
    description: "Vernis gel Canni avec brillance intense, parfait pour les poses quotidiennes.",
    category: "vernis",
    subcategory: "canni",
    price: 850,
    imageUrl: canniImage("cc2"),
    images: [canniImage("cc2")],
    stock: 20,
    canniCollection: "cc2",
    colors: [
      { name: "Nude", value: "#d9a38f" },
      { name: "Lilas", value: "#c4b5fd" },
      { name: "Vert", value: "#22c55e" },
    ],
    isNew: true,
  },
  {
    id: "canni-cc5",
    name: "Vernis Canni CC5",
    reference: "CC5",
    description: "Teinte Canni professionnelle, application fluide et fini propre après catalysation.",
    category: "vernis",
    subcategory: "canni",
    price: 850,
    imageUrl: canniImage("cc5"),
    images: [canniImage("cc5")],
    stock: 20,
    canniCollection: "cc5",
    colors: [
      { name: "Bordeaux", value: "#7f1d3f" },
      { name: "Corail", value: "#ff7f6a" },
      { name: "Rose", value: "#ec4899" },
    ],
  },
  {
    id: "canni-cc7",
    name: "Vernis Canni CC7",
    reference: "CC7",
    description: "Couleur Canni élégante pour manucures nettes, brillantes et longue tenue.",
    category: "vernis",
    subcategory: "canni",
    price: 850,
    imageUrl: canniImage("cc7"),
    images: [canniImage("cc7")],
    stock: 20,
    canniCollection: "cc7",
    colors: [
      { name: "Blanc", value: "#ffffff" },
      { name: "Beige", value: "#e8d5c4" },
      { name: "Rose pale", value: "#f8cbd5" },
    ],
    isBestSeller: true,
  },
  {
    id: "canni-cc3",
    name: "Vernis Canni CC3",
    reference: "CC3",
    description: "Collection Canni CC3 aux teintes nude, terre et élégantes pour des poses naturelles.",
    category: "vernis",
    subcategory: "canni",
    price: 850,
    imageUrl: canniImage("cc3"),
    images: [canniImage("cc3")],
    stock: 20,
    canniCollection: "cc3",
    colors: [
      { name: "Nude", value: "#d9a38f" },
      { name: "Marron", value: "#8b5e3c" },
      { name: "Beige", value: "#e8d5c4" },
    ],
  },
  {
    id: "canni-cc4",
    name: "Vernis Canni CC4",
    reference: "CC4",
    description: "Collection Canni CC4 vive et colorée avec des nuances violettes, jaunes et vertes.",
    category: "vernis",
    subcategory: "canni",
    price: 850,
    imageUrl: canniImage("cc4"),
    images: [canniImage("cc4")],
    stock: 20,
    canniCollection: "cc4",
    colors: [
      { name: "Violet", value: "#8b5cf6" },
      { name: "Jaune", value: "#facc15" },
      { name: "Orange", value: "#f97316" },
    ],
  },
  {
    id: "canni-cc6",
    name: "Vernis Canni CC6",
    reference: "CC6",
    description: "Collection Canni CC6 aux nuances brunes, dorées et profondes.",
    category: "vernis",
    subcategory: "canni",
    price: 850,
    imageUrl: canniImage("cc6"),
    images: [canniImage("cc6")],
    stock: 20,
    canniCollection: "cc6",
    colors: [
      { name: "Brun", value: "#7c4a2d" },
      { name: "Doré", value: "#d4a72c" },
      { name: "Noir", value: "#111111" },
    ],
  },
  {
    id: "canni-cc8",
    name: "Vernis Canni CC8",
    reference: "CC8",
    description: "Collection Canni CC8 lumineuse avec des couleurs pastel, nacrées et fraîches.",
    category: "vernis",
    subcategory: "canni",
    price: 850,
    imageUrl: canniImage("cc8"),
    images: [canniImage("cc8")],
    stock: 20,
    canniCollection: "cc8",
    colors: [
      { name: "Turquoise", value: "#14b8a6" },
      { name: "Rose", value: "#ec4899" },
      { name: "Argent", value: "#c0c0c0" },
    ],
    isNew: true,
  },
  {
    id: "venalisa-a2",
    name: "Vernis Venalisa A2",
    reference: "A2",
    description: "Teinte douce, application fluide, finition lumineuse pour manucures naturelles.",
    category: "vernis",
    subcategory: "venalisa",
    price: 950,
    imageUrl: images.vernis,
    images: [images.vernis, images.decoration],
    stock: 20,
    colors: [],
    isNew: true,
  },
  {
    id: "base-coat-canni",
    name: "Base Coat Canni",
    reference: "BC-CANNI",
    description: "Base adhérente pour préparer l’ongle et prolonger la tenue de votre pose.",
    category: "coats",
    subcategory: "canni",
    price: 900,
    imageUrl: images.coats,
    images: [images.coats, images.vernis],
    stock: 20,
    colors: [],
    isBestSeller: true,
  },
  {
    id: "gel-builder-venalisa",
    name: "Builder Gel Venalisa",
    reference: "BG-VENA",
    description: "Gel de construction stable, idéal pour gainage, renforcement et extensions.",
    category: "gels",
    subcategory: "venalisa",
    price: 1450,
    oldPrice: 1650,
    imageUrl: images.gels,
    images: [images.gels, images.capsules],
    stock: 20,
    colors: [],
    isNew: true,
  },
  {
    id: "pinceau-pro-liner",
    name: "Pinceau Liner Pro",
    reference: "BR-LINER",
    description: "Pinceau fin pour nail art, traits précis, french et détails décoratifs.",
    category: "pinceau",
    subcategory: "",
    price: 650,
    imageUrl: images.pinceau,
    images: [images.pinceau, images.decoration],
    stock: 20,
    colors: [],
  },
  {
    id: "capsules-soft-square",
    name: "Capsules Soft Square",
    reference: "CAP-SQ",
    description: "Capsules résistantes et faciles à limer pour un rendu net et confortable.",
    category: "capsules",
    subcategory: "",
    price: 1200,
    imageUrl: images.capsules,
    images: [images.capsules, images.pack],
    stock: 20,
    colors: [],
    isBestSeller: true,
  },
  {
    id: "poudre-chrome",
    name: "Poudre Chrome",
    reference: "CHR-01",
    description: "Effet miroir ultra lumineux pour finitions tendance et créations premium.",
    category: "decoration",
    subcategory: "poudre",
    price: 700,
    imageUrl: images.decoration,
    images: [images.decoration, images.vernis],
    stock: 20,
    colors: [],
    isNew: true,
  },
  {
    id: "lampe-uv-led",
    name: "Lampe UV LED",
    reference: "LED-48W",
    description: "Appareil de catalysation rapide avec minuterie, adapté aux gels et vernis semi-permanents.",
    category: "appareil",
    subcategory: "",
    price: 4200,
    imageUrl: images.appareil,
    images: [images.appareil, images.tools],
    stock: 20,
    colors: [],
    isBestSeller: true,
  },
  {
    id: "nail-tool-kit",
    name: "Kit Tools Manucure",
    reference: "KIT-TOOLS",
    description: "Essentiels de préparation et finition pour une pose propre et professionnelle.",
    category: "tools",
    subcategory: "",
    price: 1850,
    imageUrl: images.tools,
    images: [images.tools, images.pinceau],
    stock: 20,
    colors: [],
  },
  {
    id: "nail-glue-pro",
    name: "Pack Nails Pro",
    reference: "PACK-PRO",
    description: "Pack pratique pour completer une commande nails avec accessoires et essentiels.",
    category: "pack",
    subcategory: "",
    price: 450,
    imageUrl: images.pack,
    images: [images.pack, images.capsules],
    stock: 20,
    colors: [],
  },
];

export const WILAYAS = [
  "Adrar", "Chlef", "Laghouat", "Oum El Bouaghi", "Batna", "Bejaia", "Biskra", "Bechar", "Blida", "Bouira",
  "Tamanrasset", "Tebessa", "Tlemcen", "Tiaret", "Tizi Ouzou", "Alger", "Djelfa", "Jijel", "Setif", "Saida",
  "Skikda", "Sidi Bel Abbes", "Annaba", "Guelma", "Constantine", "Medea", "Mostaganem", "Msila", "Mascara", "Ouargla",
  "Oran", "El Bayadh", "Illizi", "Bordj Bou Arreridj", "Boumerdes", "El Tarf", "Tindouf", "Tissemsilt", "El Oued", "Khenchela",
  "Souk Ahras", "Tipaza", "Mila", "Ain Defla", "Naama", "Ain Temouchent", "Ghardaia", "Relizane",
];

export const DELIVERY_FEES = {
  domicile: 700,
  bureau: 450,
};

export function findCategoryLabel(id: string) {
  return CATEGORIES.find((category) => category.id === id)?.label ?? id;
}
